name: Lint checks

on: [push, pull_request]

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.7'
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11-dev'
        - 'pypy-3.7'
        - 'pypy-3.8'
        - 'pypy-3.9'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run lint checks
      run: make lint
      env:
        PYTHON: python${{ matrix.python-version }}
